export const GET_WINNERS_DATA = "GET_WINNERS_DATA";
export const GET_WINNERS_DATA_SUCCEEDED = "GET_WINNERS_DATA_SUCCEEDED";
export const SET_UNIQUE_YEARS = "SET_UNIQUE_YEARS";
export const SET_UNIQUE_Categories = "SET_UNIQUE_Categories";
export const ON_FILTER_APPLIED = "ON_FILTER_APPLIED";
export const SET_WINNERS_FILTERED_DATA = "SET_WINNERS_FILTERED_DATA";